use npm pack to create a release asset
and upload tarball to gh assets for easier installation

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -27,27 +27,20 @@ jobs:
           cd ../
           npm i
 
-      - name: Compile to es5 (web)
-        run: npm run webpack
+      - name: build and pack
+        run: |
+          set -e      # fail with non-zero exit code on error
+          npm run build
+          npm pack
+          mv $(ls | grep .tgz) docupilot-js-sdk.tgz
 
-      - name: Upload Release Asset (Production)
-        id: upload-release-asset-production
+      - name: Upload Release Asset
+        id: upload-release-asset
         uses: actions/upload-release-asset@v1
         env:
           GITHUB_TOKEN: ${{ secrets.RELEASE_ASSSET_PAT }}
         with:
           upload_url: ${{ github.event.release.upload_url }}
-          asset_path: ./dist/docupilot-js.es5.min.js
-          asset_name: docupilot-js.es5.min.js
-          asset_content_type: application/javascript
-
-      - name: Upload Release Asset (Development)
-        id: upload-release-asset-development
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.RELEASE_ASSSET_PAT }}
-        with:
-          upload_url: ${{ github.event.release.upload_url }}
-          asset_path: ./dist/docupilot-js.es5.js
-          asset_name: docupilot-js.es5.js
-          asset_content_type: application/javascript
+          asset_path: ./docupilot-js-sdk.tgz
+          asset_name: docupilot-js-sdk.tgz
+          asset_content_type: application/x-gtar
